import { Inter } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import BootstrapClient from '@/components/bootstrapClient/BootstrapClient';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: [
    'optimización de procesos',
    'consultora tecnológica',
    'innovación tecnológica',
    'actualización de sistemas',
    'cloud computing',
    'gestión de proyectos de TI',
    'integración de sistemas',
    'servicio de consultoría',
  ],
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <BootstrapClient />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
